SELECT OWNER, OBJECT_NAME AS Nome_Objeto, OBJECT_TYPE AS Tipo, CREATED AS "Criação", LAST_DDL_TIME "Última_Alteração" FROM DBA_OBJECTS WHERE OBJECT_NAME
IN ('CRUZ_COINCIDENCIAS', 'CRUZ_COINCIDENCIAS2', 'CRUZ_COINCIDENCIAS3')
