-- Verificar tablespace e owner
select tablespace_name, owner from all_tables where table_name = 'CPDINTER_BASECONCAPI_HISTORICO';

-- Execução
ALTER TABLE RMS.CPDINTER_BASECONCAPI_HISTORICO MOVE TABLESPACE CPDINTER_D;
ALTER TABLE NOMEDATABELA MOVE TABLESPACE TABLESPACEDESTINO;
