-- Consultar os datafiles
 SELECT
 TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
 
-- Descer a tablespace
ALTER TABLESPACE USERS OFFLINE;

-- Mover ou copiar o datafile a nível de SO da origem para o destino
MV /U02/ORADATA/TEST/USERS01.DBF /U03/ORADATA/TEST/

-- Modificar o diretório
ALTER TABLESPACE USERS RENAME DATAFILE 'C:\ORACLE_19C\ORADATA\ORCL\USERS01.DBF' TO 'D:\ORACLE\ORADATA\ORCL\USERS01.DBF';

-- Subir a tablespace
ALTER TABLESPACE USERS ONLINE;

*/
ERRO na linha 1:
ORA-01113: o arquivo 7 precisa da recuperaþÒo de mÝdia
ORA-01110: 7 do arquivo de dados: 'D:\ORACLE\ORADATA\ORCL\USERS01.DBF'
/*

-- Em caso de ORA-01113 e ORA-01110
RECOVER DATAFILE 'D:\ORACLE\ORADATA\ORCL\USERS01.DBF'

-- Tablespace UNDO, SYSTEM, SYSAUX ETC...
SHUT IMMEDIATE;

STARTUP MOUNT;

ALTER DATABASE RENAME FILE 'C:\ORACLE_19C\ORADATA\ORCL\UNDOTBS01.DBF' TO 'D:\ORACLE\ORADATA\ORCL\UNDOTBS01.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLE_19C\ORADATA\ORCL\SYSTEM01.DBF' TO 'D:\ORACLE\ORADATA\ORCL\SYSTEM01.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLE_19C\ORADATA\ORCL\SYSAUX01.DBF' TO 'D:\ORACLE\ORADATA\ORCL\SYSAUX01.DBF';
ALTER DATABASE RENAME FILE 'C:\ORACLE_19C\ORADATA\ORCL\TEMP01.DBF' TO 'D:\ORACLE\ORADATA\ORCL\TEMP01.DBF';


-- No pdb seed
shut immediate;
ALTER DATABASE RENAME FILE 'C:\oracle_19c\oradata\ORCL\pdbseed\UNDOTBS01.DBF' TO 'D:\Oracle\Oradata\ORCL\seed\UNDOTBS01.DBF';
ALTER DATABASE RENAME FILE 'C:\oracle_19c\oradata\ORCL\pdbseed\SYSTEM01.DBF' TO 'D:\Oracle\Oradata\ORCL\seed\SYSTEM01.DBF';
ALTER DATABASE RENAME FILE 'C:\oracle_19c\oradata\ORCL\pdbseed\SYSAUX01.DBF' TO 'D:\Oracle\Oradata\ORCL\seed\SYSAUX01.DBF';
ALTER DATABASE RENAME FILE 'C:\oracle_19c\oradata\ORCL\pdbseed\TEMP012022-04-14_17-07-07-308-PM.DBF' TO 'D:\Oracle\Oradata\ORCL\seed\TEMP012022-04-14_17-07-07-308-PM.DBF';

startup;
