-- Criando usuário e permissionando adequadamente
create user dbsat identified by "PdazFjgXBBtY";
grant create session to dbsat;
grant select on sys.registry$history to dbsat;
grant select_catalog_role to dbsat;
-- if Database Vault has been enabled
grant dv_secanalyst to dbsat;
-- 12c/18c/19c only
grant audit_viewer to dbsat;
grant capture_admin to dbsat;
-- 11g and 12c/18c/19c
grant select on sys.dba_users_with_defpwd to dbsat;
-- 12c/18c/19c only
grant select on audsys.aud$unified to dbsat;
exit

-- Baixando o arquivo
autentica-se no support oracle através do link abaixo
https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=233553233322032&id=2138254.1&_afrWindowMode=0&_adf.ctrl-state=14c823freu_4

-- Após copiar para o servidor onde será executado crie diretórios e desconpacte os arquivos
cd /home/oracle
mkdir dbsat
mv dbsat.zip dbsat/.
cd dbsat
unzip dbsat.zip

-- Verificando se o zip está instalado no servidor e instalando caso não esteja
yum list installed | grep zip

-- instalando
yum install zip

-- Executando o dbsat(como oracle)
cd /home/oracle/dbsat

-- Etapa de coleta
-- Dependendo da senha o prompt pode não acessar o sqlplus e essa etapa pode demorar facilmente longos minutos
nohup ./dbsat collect dbsat/PdazFjgXBBtY dbsat_RNS1 &

/*
Database Security Assessment Tool version 3.1 (Jan 2024)

This tool is intended to assist you in securing your Oracle database
system. You are solely responsible for your system and the effect and
results of the execution of this tool (including, without limitation,
any damage or data loss). Further, the output generated by this tool may
include potentially sensitive system configuration data and information
that could be used by a skilled attacker to penetrate your system. You
are solely responsible for ensuring that the output of this tool,
including any generated reports, is handled in accordance with your
company's policies.

Connecting to the target Oracle database...


SQL*Plus: Release 19.0.0.0.0 - Production on Tue Feb 13 20:20:41 2024
Version 19.16.0.0.0

Copyright (c) 1982, 2022, Oracle.  All rights reserved.

Last Successful login time: Tue Feb 13 2024 20:20:23 -03:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.16.0.0.0

Setup complete.
*/

-- Monitorando dbsat 
SELECT username,sid, serial#,
TO_CHAR(CURRENT_TIMESTAMP,'HH24:MI:SS') AS curr,
TO_CHAR(start_time,'HH24:MI:SS') AS logon,
(sysdate - start_time)*24*60 AS mins
FROM V$SESSION_LONGOPS
WHERE username = 'DBSAT'

-- Identificar PID para monitorar pelo top SO
select a.sid, a.serial#,a.username, a.osuser, b.spid
from v$session a, v$process b
where a.paddr= b.addr
and a.sid='&sid'
order by a.sid;

-- Monitorando pelo SO
ps -ef | grep dbsat
top -p PID
-- Geração do relatório com a coleta realizada
- Reporter
./dbsat report dbsat_HOMOLOG
unzip dbsat_pdb1_report.zip

-- Export java_home
export JAVA_HOME=/u01/app/oracle/product/19.0.0/dbhome_1/jdk

-- Gerando arquivo de conf da instância
cd /home/oracle/dbsat/Discover/conf
cp sample_dbsat.config instance_name_dbsat.config

-- Alterando o parâmetro DB_NAME
vi instance_name_dbsat.config – ajuste os parâmetros abaixo
###########################################################
#Use DB_HOSTNAME, DB_PORT and DB_SERVICE_NAME to connect using
#password at the prompt
#DB_IP is the IP address or FQDN for the DB Server
#default is localhost
DB_HOSTNAME = localhost
#DB_PORT is the port at which the DBSAT tool needs to connect to
#default is 1521
DB_PORT = 1521
#DB_SERVICE_NAME is the service Name for the DB
#default is empty
DB_SERVICE_NAME = instance_name
###########################################################

-- Export da variável
export PATH=$PATH:$JAVA_HOME/bin

-- Gerando relatório de dados sensiveis
cd /home/oracle/dbsat
./dbsat discover -c Discover/conf/HOMOLOG_dbsat.config HOMOLOGsensitivedata

-- Unzip report gerado
unzip DIVERSO1sensitivedata_report.zip

-- Copiar relatórios como root
cp /home/oracle/dbsat/DIVERSO1/DIVERSO1sensitivedata_discover.html /home/matheus.santos/
cp /home/oracle/dbsat/DIVERSO1/dbsat_DIVERSO1_report.html /home/matheus.santos/

-- permissão para fazer download
cd /home/matheus.santos/

37140089 376K -rw-------   1 root           root           374K Feb 15 10:50 dbsat_DIVERSO1_report.html
38271362  40K -rw-------   1 root           root            37K Feb 15 10:49 DIVERSO1sensitivedata_discover.html

chown matheus.santos:matheus.santos dbsat_DIVERSO1_report.html
chown matheus.santos:matheus.santos DIVERSO1sensitivedata_discover.html

37140089 376K -rw-------   1 matheus.santos matheus.santos 374K Feb 15 10:50 dbsat_DIVERSO1_report.html
38271362  40K -rw-------   1 matheus.santos matheus.santos  37K Feb 15 10:49 DIVERSO1sensitivedata_discover.html
